# Choose whatever you want, version >= 1.16
FROM golang:1.24-alpine

WORKDIR /app

RUN go install github.com/air-verse/air@latest

# Install Chromium and dependencies
RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    harfbuzz \
    ttf-freefont \
    ca-certificates \
    bash

COPY go.mod go.sum ./
RUN go mod download

CMD ["air"]
