// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AutomationRule struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	Name            string
	CompanyFilter   pgtype.Text
	LocationFilter  pgtype.Text
	ActionType      string
	MessageTemplate pgtype.Text
	IsActive        bool
	CreatedAt       pgtype.Timestamp
}

type Company struct {
	ID          pgtype.UUID
	Name        string
	LinkedinUrl pgtype.Text
	Industry    pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type ConnectionRelationship struct {
	ID                 pgtype.UUID
	ProfileAID         pgtype.UUID
	ProfileBID         pgtype.UUID
	Degree             int32
	DiscoveredAt       pgtype.Timestamp
	DiscoveredByUserID pgtype.UUID
}

type LinkedinProfile struct {
	ID               pgtype.UUID      `json:"id" db:"id"`
	LinkedinUrl      pgtype.Text      `json:"linkedin_url" db:"linkedin_url"`
	LinkedinID       pgtype.Text      `json:"linkedin_id" db:"linkedin_id"`
	Name             string           `json:"name" db:"name"`
	Location         pgtype.Text      `json:"location" db:"location"`
	CurrentCompanyID pgtype.UUID      `json:"current_company_id" db:"current_company_id"`
	Headline         pgtype.Text      `json:"headline" db:"headline"`
	CreatedAt        pgtype.Timestamp `json:"created_at" db:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at" db:"updated_at"`
}

type ProfileCompany struct {
	ID        pgtype.UUID
	ProfileID pgtype.UUID
	CompanyID pgtype.UUID
	Position  string
	StartDate pgtype.Date
	EndDate   pgtype.Date
	IsCurrent bool
	CreatedAt pgtype.Timestamp
}

type TrackedConnection struct {
	ID            pgtype.UUID
	UserID        pgtype.UUID
	ProfileID     pgtype.UUID
	CreatedAt     pgtype.Timestamp
	LastCheckedAt pgtype.Timestamp
}

type User struct {
	ID           pgtype.UUID
	Email        string
	Name         string
	PasswordHash pgtype.Text
	GoogleID     pgtype.Text
	AccessToken  pgtype.Text
	RefreshToken pgtype.Text
	AuthType     string
	IsActive     bool
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}
